from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import classification_report, confusion_matrix
import pickle
import numpy as np
import pandas as pd
import os

TRAINING_DATA = [
    # Plastique (0)
    ("bouteille en plastique", 0),
    ("sac plastique", 0),
    ("emballage plastique", 0),
    ("bouteille d'eau en plastique", 0),
    ("sac de courses en plastique", 0),
    ("pot de yaourt", 0),
    ("barquette en plastique", 0),
    ("film plastique", 0),
    ("bouteille de lait plastique", 0),
    ("bouchon en plastique", 0),
    ("tube en plastique", 0),
    ("gobelet en plastique", 0),
    ("couvercle plastique", 0),
    ("paquet en plastique", 0),
    ("sachet plastique", 0),
    ("sachet alimentaire plastique", 0),
    ("flacon plastique", 0),
    ("pot à épices en plastique", 0),
    ("bouteille d'huile plastique", 0),
    ("couvercle de boîte plastique", 0),
    ("conteneur plastique", 0),
    ("bouteille de soda plastique", 0),
    ("bouteille de jus plastique", 0),
    ("bouteille en PET", 0),
    ("verre en plastique", 0),
    ("gobelets en plastique", 0),
    ("film alimentaire plastique", 0),
    ("barquette alimentaire", 0),
    ("pot de crème plastique", 0),
    ("flacon de shampoing plastique", 0),
    ("tube de dentifrice", 0),
    ("bouteille de vinaigre plastique", 0),
    ("gobelet de café plastique", 0),
    ("sachet congélation", 0),
    ("bouteille de sauce plastique", 0),
    ("pot de beurre plastique", 0),
    ("bouteille de lait PET", 0),
    ("flacon de détergent", 0),
    ("paquet de bonbons plastique", 0),
    ("bouteille de sirop plastique", 0),
    ("pot de crème glacée plastique", 0),
    ("barquette repas plastique", 0),
    ("verres jetables plastique", 0),
    ("sachet à pain plastique", 0),
    ("pot à yaourt plastique", 0),
    ("couvercle pot plastique", 0),
    ("bouteille d'eau PET", 0),
    ("flacon liquide vaisselle", 0),
    ("tube colle plastique", 0),
    ("pot peinture plastique", 0),
    ("sachet de chips", 0),
    ("gobelet lait plastique", 0),
    ("emballage alimentaire plastique", 0),
    ("bouteille soda PET", 0),
    ("barquette charcuterie plastique", 0),
    ("tube ketchup plastique", 0),
    ("flacon huile plastique", 0),
    ("bouteille lait UHT", 0),
    ("couvercle plastique alimentaire", 0),
    ("sachet bonbons plastique", 0),
    ("pot crème visage plastique", 0),
    ("gobelet cocktail plastique", 0),
    ("barquette sushi plastique", 0),
    ("bouteille jus PET", 0),
    ("tube dentifrice plastique", 0),
    ("flacon parfum plastique", 0),
    ("pot confiture plastique", 0),
    ("bouteille vinaigre PET", 0),
    ("sac congélation plastique", 0),
    ("flacon shampooing plastique", 0),
    ("bouteille boisson énergétique", 0),
    ("gobelet café jetable", 0),
    ("bouteille sauce soja plastique", 0),
    ("tube mayonnaise plastique", 0),
    ("barquette fromage plastique", 0),
    ("pot glace plastique", 0),
    ("flacon lait infantile", 0),
    ("bouteille sirop PET", 0),
    ("gobelets plastique colorés", 0),
    ("tube crème solaire plastique", 0),
    ("flacon gel douche plastique", 0),
    ("sachet chips snack", 0),
    ("pot beurre cacahuète plastique", 0),
    ("bouteille ketchup PET", 0),
    ("barquette repas micro-ondes", 0),
    ("tube dentifrice voyage", 0),
    ("flacon liquide vaisselle", 0),
    ("bouteille boisson gazeuse", 0),
    ("sachet emballage alimentaire", 0),
    ("pot yaourt plastique", 0),
    ("couvercle pot plastique", 0),
    ("barquette traiteur plastique", 0),
    ("bouteille d'eau sport", 0),
    ("flacon huile alimentaire", 0),
    ("gobelet lait plastique", 0),
    ("tube crème plastique", 0),
    ("bouteille soda PET", 0),
    ("sachet alimentaire jetable", 0),
    ("barquette alimentaire plastique", 0),
    ("flacon liquide plastique", 0),

    # Verre (1)
    ("bouteille en verre", 1),
    ("pot en verre", 1),
    ("bocal en verre", 1),
    ("bouteille de vin", 1),
    ("pot de confiture", 1),
    ("verre à boire cassé", 1),
    ("flacon en verre", 1),
    ("bouteille de jus en verre", 1),
    ("verre à vin", 1),
    ("ampoule en verre", 1),
    ("verre à eau", 1),
    ("bouteille de bière", 1),
    ("carafe en verre", 1),
    ("bouteille de champagne", 1),
    ("flacon parfum", 1),
    ("bocal alimentaire", 1),
    ("verre à liqueur", 1),
    ("verre brisé", 1),
    ("bouteille de soda en verre", 1),
    ("gobelet en verre", 1),
    ("vase en verre", 1),
    ("tasse en verre", 1),
    ("bouteille de lait en verre", 1),
    ("bouteille de jus de fruit en verre", 1),
    ("pot de miel en verre", 1),
    ("pot de sauce en verre", 1),
    ("flacon médical en verre", 1),
    ("ampoule cassée", 1),
    ("bocal à épices", 1),
    ("verre à cocktail", 1),
    ("verre à bière", 1),
    ("bouteille de soda cassée", 1),
    ("verres à vin", 1),
    ("flacon bouteille en verre", 1),
    ("bouteille confiture verre", 1),
    ("bouteille liqueur verre", 1),
    ("verre de table", 1),
    ("bouteille de lait", 1),
    ("flacon parfum cassé", 1),
    ("verres brisés", 1),
    ("bouteille eau minérale", 1),
    ("verre vin rouge", 1),
    ("carafe eau", 1),
    ("verre cocktail", 1),
    ("bouteille jus orange", 1),
    ("bouteille soda", 1),
    ("bocal confiture", 1),
    ("flacon médicament", 1),
    ("verre cassé", 1),
    ("ampoule verre usagée", 1),
    ("bouteille bière", 1),
    ("pot confiture", 1),
    ("gobelet verre", 1),
    ("verre eau cassé", 1),
    ("bouteille vin rouge", 1),
    ("bocal à cornichons", 1),
    ("flacon huile essentielle", 1),
    ("verre jus", 1),
    ("verre chocolat chaud", 1),
    ("flacon cosmétique", 1),
    ("bouteille soda cola", 1),
    ("bouteille eau plate", 1),
    ("carafe vin", 1),
    ("verre whisky", 1),
    ("bouteille bière brune", 1),
    ("verres eau", 1),
    ("flacon parfum vide", 1),
    ("bouteille lait verre", 1),
    ("bocal sauce", 1),
    ("verre chocolat", 1),
    ("verre thé", 1),
    ("ampoule halogène", 1),
    ("bouteille champagne vide", 1),
    ("verre cocktail cassé", 1),
    ("bouteille jus pomme", 1),
    ("bouteille jus raisin", 1),
    ("bouteille soda gazeuse", 1),
    ("flacon lotion", 1),
    ("bouteille boisson", 1),
    ("bocal cornichons", 1),
    ("verre vin blanc", 1),
    ("verres cocktail", 1),
    ("bouteille vinaigre", 1),
    ("flacon médicament vide", 1),
    ("pot miel", 1),
    ("bouteille soda vide", 1),
    ("verre jus cassé", 1),
    ("bouteille bière vide", 1),
    ("bocal sauce tomate", 1),
    ("flacon huile verre", 1),
    ("bouteille boisson alcoolisée", 1),
    ("verre boisson", 1),
    ("ampoule fluorescente", 1),
    ("bouteille soda cassée", 1),
    ("verre eau vide", 1),
    ("bouteille vin vide", 1),
    ("flacon cosmétique vide", 1),
    ("verre cocktail vide", 1),
    ("bouteille jus vide", 1),
    ("bouteille bière brune vide", 1),
    ("bouteille champagne cassée", 1),
    ("verre whisky vide", 1),
    ("bouteille eau gazeuse", 1),
    ("bocal confiture vide", 1),
    ("flacon parfum cassé", 1),
    ("verre eau potable", 1),
    ("bouteille vin rouge vide", 1),
    ("bouteille soda sucre", 1),
    ("verres champagne", 1),
    ("bouteille lait frais", 1),
    ("flacon médical", 1),
    ("bocal sauce barbecue", 1),
    ("verre jus frais", 1),
    ("bouteille boisson gazeuse", 1),
    ("bouteille soda brune", 1),
    ("verre vin rouge vide", 1),

    
    # Papier (2)
    ("journal", 2),
    ("magazine", 2),
    ("boîte en carton", 2),
    ("carton", 2),
    ("papier", 2),
    ("enveloppe", 2),
    ("livre", 2),
    ("cahier", 2),
    ("emballage carton", 2),
    ("boîte de céréales", 2),
    ("flyer", 2),
    ("brochure", 2),
    ("papier journal", 2),
    ("papier publicitaire", 2),
    ("feuille blanche", 2),
    ("feuille de cahier", 2),
    ("carton ondulé", 2),
    ("boîte en carton pliée", 2),
    ("carton alimentaire", 2),
    ("livret", 2),
    ("bulletin", 2),
    ("manuels scolaires", 2),
    ("papier à lettre", 2),
    ("enveloppes usagées", 2),
    ("journal usagé", 2),
    ("magazines usagés", 2),
    ("feuilles mortes papier", 2),
    ("emballage en papier", 2),
    ("carton de pizza", 2),
    ("boîte en carton brun", 2),
    ("carton de lait", 2),
    ("papier recyclé", 2),
    ("journal plié", 2),
    ("feuille imprimée", 2),
    ("livre ancien", 2),
    ("brochure touristique", 2),
    ("flyer promotionnel", 2),
    ("cahier usagé", 2),
    ("boîte carton recyclée", 2),
    ("papier kraft", 2),
    ("carton à emballer", 2),
    ("manuscrit", 2),
    ("journal déchiré", 2),
    ("papier journal froissé", 2),
    ("papier brouillon", 2),
    ("feuilles A4", 2),
    ("brochure informative", 2),
    ("cahier d'école", 2),
    ("livret scolaire", 2),
    ("enveloppe vide", 2),
    ("papier cadeau", 2),
    ("carton ondulé vide", 2),
    ("papier administratif", 2),
    ("flyer publicitaire", 2),
    ("boîte carton ouverte", 2),
    ("carton alimentaire usagé", 2),
    ("feuille de magazine", 2),
    ("brochure publicitaire", 2),
    ("papier de soie", 2),
    ("journal local", 2),
    ("livre abîmé", 2),
    ("cahier papier recyclé", 2),
    ("feuilles volantes", 2),
    ("boîte carton ferme", 2),
    ("papier imprimante", 2),
    ("carton plié", 2),
    ("brochure voyage", 2),
    ("flyer événement", 2),
    ("journal quotidien", 2),
    ("livre de poche", 2),
    ("cahier neuf", 2),
    ("papier ancien", 2),
    ("carton d'emballage", 2),
    ("boîte carton ferme", 2),
    ("feuille usagée", 2),
    ("journal magazine", 2),
    ("papier peint", 2),
    ("brochure culturelle", 2),
    ("flyer promotionnel", 2),
    ("cahier scolaire", 2),
    ("livre scolaire", 2),
    ("papier recyclé blanc", 2),
    ("carton léger", 2),
    ("boîte carton épais", 2),
    ("feuille manuscrite", 2),
    ("journal plié", 2),
    ("brochure informative pliée", 2),
    ("flyer événementiel", 2),
    ("cahier couvert", 2),
    ("livre couvert", 2),
    ("papier couleur", 2),
    ("carton robuste", 2),
    ("boîte carton brun", 2),
    ("feuille brouillon", 2),
    ("journal abîmé", 2),
    ("brochure usagée", 2),
    ("flyer déchiré", 2),
    ("cahier ancien", 2),
    ("livre ancien", 2),
    
    # Métal (3)
    ("canette", 3),
    ("boîte de conserve", 3),
    ("cannette en aluminium", 3),
    ("couvercle métallique", 3),
    ("canette de soda", 3),
    ("boîte de thon", 3),
    ("capsule métallique", 3),
    ("canette de bière", 3),
    ("pièce de monnaie", 3),
    ("aluminium", 3),
    ("couvercle boîte métal", 3),
    ("boîte métallique vide", 3),
    ("capsule bouteille", 3),
    ("canette vide", 3),
    ("ustensile en métal", 3),
    ("clou", 3),
    ("écrou", 3),
    ("boulon", 3),
    ("casserole métal", 3),
    ("poêle métal", 3),
    ("cuillère métal", 3),
    ("fourchette métal", 3),
    ("couverts métal", 3),
    ("bouteille capsule métal", 3),
    ("boîte conserve ouverte", 3),
    ("aluminium recyclé", 3),
    ("canette soda vide", 3),
    ("canette bière vide", 3),
    ("boîte thon métal", 3),
    ("capsule métal usagée", 3),
    ("objet métallique", 3),
    ("ferraille", 3),
    ("grille métallique", 3),
    ("clou rouillé", 3),
    ("vis métallique", 3),
    ("boulon rouillé", 3),
    ("écrou métallique", 3),
    ("couvercle métal recyclé", 3),
    ("boîte métal alimentaire", 3),
    ("capsule bouteille bière", 3),
    ("canette boisson", 3),
    ("couvercle métallique usagé", 3),
    ("canette soda", 3),
    ("bouteille capsule métallique", 3),
    ("pièces métalliques", 3),
    ("alu", 3),
    ("ferraille domestique", 3),
    ("couvercle boîte", 3),
    ("boîte métal", 3),
    ("capsule métal", 3),
    ("canette vide métal", 3),
    ("canette boisson métallique", 3),
    ("boîte conserve métal", 3),
    ("couvercle métal alimentaire", 3),
    ("capsule bouteille vide", 3),
    ("objet métal recyclé", 3),
    ("bouteille capsule aluminium", 3),
    ("canette boisson vide", 3),
    ("couvercle boîte métal", 3),
    ("boîte métal vide", 3),
    ("capsule métal usée", 3),
    ("ustensiles métalliques", 3),
    ("clous", 3),
    ("vis", 3),
    ("pièces métal", 3),
    ("boulons", 3),
    ("écrous", 3),
    ("grilles métalliques", 3),
    ("casserole métal usagée", 3),
    ("poêle métal usagée", 3),
    ("couverts métal usagés", 3),
    ("cuillère métal usée", 3),
    ("fourchette métal usée", 3),
    ("boîte conserve rouillée", 3),
    ("canette métal rouillée", 3),
    ("capsule bouteille métal", 3),
    ("boîte métallique recyclable", 3),
    ("capsule métallique usagée", 3),
    ("couvercle métal usé", 3),
    ("pièce métal usagée", 3),
    ("alu usagé", 3),
    ("ferraille métal", 3),
    ("canette aluminium vide", 3),
    ("bouteille capsule aluminium", 3),
    ("boîte conserve aluminium", 3),
    ("couvercle boite métal", 3),
    ("capsule bouteille métal vide", 3),
    ("canette soda métal", 3),
    ("bouteille capsule métal vide", 3),
    ("objets métalliques", 3),
    ("couvercle aluminium", 3),
    ("boîte métal usagée", 3),
    ("canette boisson métal", 3),
    ("capsule métal brisée", 3),
    ("bouteille capsule métal usée", 3),
    ("canette bière métal", 3),
    ("boîte thon métal", 3),
    ("capsule bouteille bière", 3),
    ("ustensiles métal usagés", 3),
    ("casserole métal usée", 3),
    ("poêle métal usée", 3),
    
    # Organique (4)
    ("épluchures", 4),
    ("reste de nourriture", 4),
    ("fruits pourris", 4),
    ("légumes abîmés", 4),
    ("marc de café", 4),
    ("coquilles d'œuf", 4),
    ("pain rassis", 4),
    ("feuilles mortes", 4),
    ("pelure de banane", 4),
    ("trognon de pomme", 4),
    ("restes de repas", 4),
    ("noyau de pêche", 4),
    ("reste de légumes", 4),
    ("restes de fruits", 4),
    ("marc de thé", 4),
    ("épluchures de pomme de terre", 4),
    ("coquille d'œuf cassée", 4),
    ("restes alimentaires", 4),
    ("peau de fruits", 4),
    ("banane abîmée", 4),
    ("reste de viande", 4),
    ("restes de poisson", 4),
    ("noyau de fruit", 4),
    ("pelure d'orange", 4),
    ("café moulu usagé", 4),
    ("reste de salade", 4),
    ("peau de légumes", 4),
    ("épluchures diverses", 4),
    ("restes de repas froids", 4),
    ("fruits pourris divers", 4),
    ("légumes pourris", 4),
    ("marc café humide", 4),
    ("coquille œuf usée", 4),
    ("pain sec", 4),
    ("feuilles mortes jardin", 4),
    ("pelure pomme", 4),
    ("trognon pomme", 4),
    ("restes repas chaud", 4),
    ("noyaux fruits", 4),
    ("épluchures pomme de terre", 4),
    ("marc café sec", 4),
    ("reste légumes crus", 4),
    ("peau fruits divers", 4),
    ("reste viande cuite", 4),
    ("restes poisson cru", 4),
    ("noyau pêche", 4),
    ("pelure banane", 4),
    ("reste salade cuite", 4),
    ("fruits pourris frais", 4),
    ("légumes abîmés frais", 4),
    ("marc thé humide", 4),
    ("coquille œuf fraîche", 4),
    ("pain rassis dur", 4),
    ("feuilles mortes humide", 4),
    ("pelures fruits", 4),
    ("trognon pomme frais", 4),
    ("restes repas divers", 4),
    ("noyau fruits divers", 4),
    ("épluchures légumes", 4),
    ("marc café mouillé", 4),
    ("reste légumes cuits", 4),
    ("peau fruits frais", 4),
    ("reste viande froide", 4),
    ("restes poisson frais", 4),
    ("noyaux pêche", 4),
    ("pelures oranges", 4),
    ("reste salade fraiche", 4),
    ("marc café journée", 4),
    ("coquilles œufs", 4),
    ("pain rassis durci", 4),
    ("feuilles mortes séchées", 4),
    ("pelure pomme banane", 4),
    ("trognon pomme abîmé", 4),
    ("restes repas soir", 4),
    ("noyau pêche frais", 4),
    ("épluchures fruits divers", 4),
    ("marc thé sec", 4),
    ("reste légumes frais", 4),
    ("peau fruits secs", 4),
    ("reste viande abîmée", 4),
    ("restes poisson abîmé", 4),
    ("noyaux fruits divers", 4),
    ("pelure banane abîmée", 4),
    ("reste salade soir", 4),
    ("fruits pourris abîmés", 4),
    ("légumes pourris abîmés", 4),
    ("marc café sec humide", 4),
    ("coquille œuf abîmée", 4),
    ("pain dur rassis", 4),
    ("feuilles mortes sèches", 4),
    ("pelure fruits divers", 4),
    ("trognon pomme abîmé", 4),
    ("restes repas matin", 4),
    ("noyau pêche abîmé", 4),
    ("épluchures légumes divers", 4),
    ("marc café utilisé", 4),

    # Autre (5)
    ("pile usagée", 5),
    ("ampoule", 5),
    ("déchet dangereux", 5),
    ("médicament périmé", 5),
    ("mégot de cigarette", 5),
    ("polystyrène", 5),
    ("couche", 5),
    ("mouchoir usagé", 5),
    ("produit chimique", 5),
    ("objet électronique cassé", 5),
    ("batterie", 5),
    ("thermomètre cassé", 5),
    ("déchet toxique", 5),
    ("tube de colle usé", 5),
    ("aérosol vide", 5),
    ("ampoule halogène", 5),
    ("déchet médical", 5),
    ("pile bouton", 5),
    ("chargeur cassé", 5),
    ("appareil électrique cassé", 5),
    ("mouchoirs usés", 5),
    ("cartouche d'encre vide", 5),
    ("produit chimique dangereux", 5),
    ("médicament expiré", 5),
    ("objet dangereux", 5),
    ("déchets électroniques", 5),
    ("couche sale", 5),
    ("mégot", 5),
    ("pile alcaline usagée", 5),
    ("bouteille spray vide", 5),
    ("aérosol chimique", 5),
    ("batterie usagée", 5),
    ("lampes fluocompactes", 5),
    ("thermomètre mercury", 5),
    ("produit corrosif", 5),
    ("circuit électronique cassé", 5),
    ("chargeur téléphone cassé", 5),
    ("pile rechargeable vide", 5),
    ("appareil électronique défectueux", 5),
    ("mouchoir sale", 5),
    ("tube peinture vide", 5),
    ("déchet hospitalier", 5),
    ("médicament inutilisable", 5),
    ("objet cassé", 5),
    ("déchets toxiques", 5),
    ("ampoule LED cassée", 5),
    ("pile plate usagée", 5),
    ("chargeur USB cassé", 5),
    ("thermomètre cassé mercury", 5),
    ("aérosol peinture vide", 5),
    ("batterie lithium vide", 5),
    ("produit chimique usagé", 5),
    ("appareil électrique défectueux", 5),
    ("couche humide", 5),
    ("mégot de tabac", 5),
    ("pile usée", 5),
    ("déchet dangereux chimique", 5),
    ("ampoule brûlée", 5),
    ("bouteille aérosol vide", 5),
    ("produit toxique", 5),
    ("objet électronique endommagé", 5),
    ("tube colle sec", 5),
    ("médicament périmé inutilisable", 5),
    ("appareil cassé", 5),
    ("pile usagée alcaline", 5),
    ("mouchoir sale usé", 5),
    ("déchets chimiques", 5),
    ("chargeur batterie cassé", 5),
    ("thermomètre liquide", 5),
    ("batterie bouton vide", 5),
    ("ampoule fluorescente cassée", 5),
    ("pile pile bouton usée", 5),
    ("couche bébé sale", 5),
    ("produit chimique domestique", 5),
    ("objet électrique endommagé", 5),
    ("appareil électronique hors service", 5),
    ("mégot cigarette jeté", 5),
    ("pile usée alcaline", 5),
    ("déchet toxique chimique", 5),
    ("ampoule cassée LED", 5),
    ("bouteille spray usagée", 5),
    ("tube peinture sec", 5),
    ("produit chimique périmé", 5),
    ("appareil électrique cassé", 5),
    ("chargeur téléphonique cassé", 5),
    ("pile lithium vide", 5),
    ("ampoule LED vide", 5),
    ("mouchoir usé", 5),
    ("déchets dangereux domestiques", 5),
    ("pile bouton usagée", 5),
    ("appareil cassé électrique", 5),
    ("thermomètre vide", 5),
    ("bouteille aérosol usagée", 5),
    ("produit chimique dangereux domestique", 5),
    ("objet électronique inutilisable", 5),
    ("couche souillée", 5),
    ("mégot jeté", 5),
]

def create_expanded_dataset():
    expanded_data = list(TRAINING_DATA)
    
    variations = [
        "un ", "une ", "des ", "le ", "la ", "les ",
        "mon ", "ma ", "mes ", "vieux ", "vieille ", "usé "
    ]
    
    for text, label in TRAINING_DATA[:30]:
        for var in variations[:3]:
            expanded_data.append((var + text, label))
    
    return expanded_data

def train_text_classifier(save_vectorizer='models/text_vectorizer.pkl', 
                          save_model='models/waste_classifier_text.pkl'):

    print("Préparation des données...")
    
    data = create_expanded_dataset()
    texts, labels = zip(*data)
    
    print(f"Dataset créé: {len(texts)} exemples")
    
    X_train, X_test, y_train, y_test = train_test_split(
        texts, labels, test_size=0.2, random_state=42, stratify=labels
    )
    
    print("\nVectorisation du texte...")
    vectorizer = TfidfVectorizer(
        max_features=100,
        ngram_range=(1, 2),
        min_df=1,
        lowercase=True
    )
    
    X_train_vec = vectorizer.fit_transform(X_train)
    X_test_vec = vectorizer.transform(X_test)
    
    print(f"Vocabulaire: {len(vectorizer.get_feature_names_out())} features")
    
    models = {
        'Naive Bayes': MultinomialNB(),
        'Logistic Regression': LogisticRegression(max_iter=1000, random_state=42),
        'Random Forest': RandomForestClassifier(n_estimators=100, random_state=42)
    }
    
    print("\nEntraînement des modèles...")
    best_model = None
    best_score = 0
    best_name = ""
    
    for name, model in models.items():
        print(f"\n--- {name} ---")
        
        model.fit(X_train_vec, y_train)
        
        train_score = model.score(X_train_vec, y_train)
        test_score = model.score(X_test_vec, y_test)
        
        cv_scores = cross_val_score(model, X_train_vec, y_train, cv=3)
        
        print(f"Score d'entraînement: {train_score:.2%}")
        print(f"Score de test: {test_score:.2%}")
        print(f"Score CV (moyenne): {cv_scores.mean():.2%} (+/- {cv_scores.std():.2%})")
        
        if test_score > best_score:
            best_score = test_score
            best_model = model
            best_name = name
    
    print(f"\nMeilleur modèle: {best_name} ({best_score:.2%})")
    
    print("\nRapport de classification (meilleur modèle):")
    y_pred = best_model.predict(X_test_vec)
    print(classification_report(y_test, y_pred, 
                                target_names=['Plastique', 'Verre', 'Papier', 'Métal', 'Organique', 'Autre']))
    
    os.makedirs('models', exist_ok=True)
    
    with open(save_vectorizer, 'wb') as f:
        pickle.dump(vectorizer, f)
    print(f"\nVectoriseur sauvegardé: {save_vectorizer}")
    
    with open(save_model, 'wb') as f:
        pickle.dump(best_model, f)
    print(f"Modèle sauvegardé: {save_model}")
    
    return vectorizer, best_model

def test_classifier(vectorizer, model):
    print("\nTest du classificateur:")
    
    test_examples = [
    # Plastique
    "gobelet de soda en plastique",
    "sachet plastique pour sandwich",
    "film alimentaire plastique",
    "tube de dentifrice vide",
    "bouteille de jus plastique",
    
    # Verre
    "verre de vin rouge",
    "pot en verre pour confiture maison",
    "flacon parfum cassé",
    "bouteille de bière vide en verre",
    "carafe d'eau en verre",
    
    # Papier
    "page de magazine déchirée",
    "cahier de mathématiques usé",
    "carton de biscuits vide",
    "brochure touristique de Paris",
    "papier cadeau coloré",
    
    # Métal
    "canette de soda vide",
    "boîte de conserve de tomates",
    "couvercle aluminium",
    "pièces de monnaie rouillées",
    "boulons métalliques",
    
    # Organique
    "pelure de kiwi",
    "reste de salade de fruits",
    "noyau d'abricot",
    "marc de café humide",
    "épluchures de carottes",
    
    # Autre
    "ampoule LED brûlée",
    "pile lithium usagée",
    "mouchoir jeté",
    "couche souillée de bébé",
    "déchet chimique domestique",
    
    # phrases plus complexes
    "bouteille en plastique de soda vide",
    "vieille boîte en carton de céréales",
    "restes de fruits pourris dans la poubelle",
    "canette de bière ouverte sur le comptoir",
    "journal déchiré et froissé",
    "ampoule halogène cassée",
    "coquille d'œuf dans le compost",
    "cartouche d'encre vide",
    "flacon en verre pour parfum",
    "sachet plastique transparent pour sandwich",
    ]

    
    categories = ['Plastique', 'Verre', 'Papier', 'Métal', 'Organique', 'Autre']
    
    for text in test_examples:
        text_vec = vectorizer.transform([text])
        prediction = model.predict(text_vec)[0]
        proba = model.predict_proba(text_vec)[0]
        
        print(f"\n'{text}'")
        print(f"  → Prédiction: {categories[prediction]}")
        print(f"  → Confiance: {proba[prediction]:.2%}")

if __name__ == "__main__":
    print("Entraînement du modèle de classification de texte\n")
    
    vectorizer, model = train_text_classifier()
    
    test_classifier(vectorizer, model)
    
    print("\nEntraînement terminé avec succès")